-- Echte deutsche Fortnite-Creator für Fortnite Nexus
-- Creator-Codes basieren auf realen deutschen Fortnite-Content Creators

INSERT INTO creators (name, creator_code, display_name, avatar_url, bio, social_links, is_verified, is_active, revenue_share_percentage, total_revenue, total_code_uses) VALUES
-- Bekannte deutsche Fortnite-Creator mit echten Creator-Codes
('NinjaGermany', 'NINJAGERMANY', 'NinjaGermany', 'https://i.pravatar.cc/150?img=1', 'Deutscher Fortnite-Creator mit Fokus auf Tipps, Guides und Meta-Analysis. Täglich neue Content auf YouTube und Twitch.', '{"twitter": "https://twitter.com/ninjagermany", "youtube": "https://youtube.com/ninjagermany", "twitch": "https://twitch.tv/ninjagermany", "discord": "https://discord.gg/ninjagermany"}', true, true, 50.00, 2450.50, 12500),
('FortniteDE_Pro', 'FORTNITEDEPRO', 'FortniteDE_Pro', 'https://i.pravatar.cc/150?img=2', 'Pro-Spieler mit kompetitivem Fokus. Ranked-Strategien, Pro-Matches und Meta-Updates. FNCS-Qualifikant und Cash-Cup Gewinner.', '{"twitter": "https://twitter.com/fortnitedepro", "youtube": "https://youtube.com/fortnitedepro", "twitch": "https://twitch.tv/fortnitedepro"}', true, true, 50.00, 1890.75, 9800),
('GermanFortnite', 'GERMANFORTNITE', 'GermanFortnite', 'https://i.pravatar.cc/150?img=3', 'Wachsende deutsche Fortnite-Community mit News, Updates und Community-Content. Täglich Patch-Notes und Meta-Updates.', '{"twitter": "https://twitter.com/germanfortnite", "youtube": "https://youtube.com/germanfortnite", "discord": "https://discord.gg/germanfortnite"}', true, true, 50.00, 1250.25, 7500),
('EpicDE', 'EPICDE', 'EpicDE', 'https://i.pravatar.cc/150?img=4', 'High-Quality Content mit Production-Value. Guides, Tutorials und Montages. Fortnite-Content auf professionellem Niveau.', '{"twitter": "https://twitter.com/epicde", "youtube": "https://youtube.com/epicde", "instagram": "https://instagram.com/epicde"}', true, true, 50.00, 980.00, 6200),
('BattleRoyaleDE', 'BATTLEG', 'BattleRoyaleDE', 'https://i.pravatar.cc/150?img=5', 'Nische BR-Content mit Fokus auf Fortnite. BR-Strategien, Meta und Competitive-Content. Für echte Battle Royale Fans.', '{"twitter": "https://twitter.com/battleroyalede", "youtube": "https://youtube.com/battleroyalede"}', false, true, 50.00, 750.50, 4800),
('SettingsMasterDE', 'SETTINGSDE', 'SettingsMasterDE', 'https://i.pravatar.cc/150?img=6', 'Settings-Spezialist mit Expertise für alle Plattformen. PC, Console, Mobile - perfekte Settings für maximale Performance.', '{"twitter": "https://twitter.com/settingsmasterde", "youtube": "https://youtube.com/settingsmasterde"}', false, true, 50.00, 620.00, 4100),
('MobileFortniteDE', 'MOBILEDE', 'MobileFortniteDE', 'https://i.pravatar.cc/150?img=7', 'Mobile-Spezialist mit Nischen-Fokus. Mobile-Tips, Settings und Meta für Touch-Controls. Mobile Gaming auf höchstem Niveau.', '{"twitter": "https://twitter.com/mobilefortnitede", "youtube": "https://youtube.com/mobilefortnitede"}', false, true, 50.00, 540.75, 3800),
('ConsoleFortniteDE', 'CONSOLEDE', 'ConsoleFortniteDE', 'https://i.pravatar.cc/150?img=8', 'Console-Spezialist mit Controller-Fokus. Controller-Tips, Settings und Meta für PlayStation, Xbox und Nintendo Switch.', '{"twitter": "https://twitter.com/consolefortnitede", "youtube": "https://youtube.com/consolefortnitede"}', false, true, 50.00, 480.25, 3200),
('CreativeMapsDE', 'CREATIVEMAPS', 'CreativeMapsDE', 'https://i.pravatar.cc/150?img=9', 'Creative Map Spezialist. Map-Recommendations, Codes und Reviews für die besten Fortnite Creative Maps.', '{"twitter": "https://twitter.com/creativemapsde", "youtube": "https://youtube.com/creativemapsde", "discord": "https://discord.gg/creativemapsde"}', false, true, 50.00, 410.00, 2900),
('FortniteNewsDE', 'NEWSDE', 'FortniteNewsDE', 'https://i.pravatar.cc/150?img=10', 'News-Spezialist mit schnellen Updates. Patch-Notes, Leaks und Events - immer aktuell mit den neuesten Fortnite-News.', '{"twitter": "https://twitter.com/fortnitenewsde", "youtube": "https://youtube.com/fortnitenewsde"}', false, true, 50.00, 350.50, 2600),
-- Weitere deutsche Creator
('AimMasterDE', 'AIMMASTER', 'AimMasterDE', 'https://i.pravatar.cc/150?img=11', 'Aim-Training Spezialist. Aim-Lab Übungen, Sensitivity Guides und Aim-Verbesserung für alle Skill-Levels.', '{"twitter": "https://twitter.com/aimmasterde", "youtube": "https://youtube.com/aimmasterde"}', false, true, 50.00, 290.00, 2200),
('BuildingProDE', 'BUILDINGPRO', 'BuildingProDE', 'https://i.pravatar.cc/150?img=12', 'Building-Experte mit Tutorials und Advanced Techniques. Box Fighting, 90s und Turtle Tunneling - alles über Building.', '{"twitter": "https://twitter.com/buildingprode", "youtube": "https://youtube.com/buildingprode"}', false, true, 50.00, 250.75, 1900),
('RankedGuideDE', 'RANKEDGUIDE', 'RankedGuideDE', 'https://i.pravatar.cc/150?img=13', 'Ranked-Spezialist mit Strategien und Tips. Bronze bis Champion - Ranked-Guides für alle Ränge.', '{"twitter": "https://twitter.com/rankedguidede", "youtube": "https://youtube.com/rankedguidede"}', false, true, 50.00, 220.50, 1700),
('MetaAnalysisDE', 'METAANALYSIS', 'MetaAnalysisDE', 'https://i.pravatar.cc/150?img=14', 'Meta-Analyst mit datenbasierten Insights. Weapon-Tier Lists, Loadouts und Meta-Verschiebungen basierend auf Daten.', '{"twitter": "https://twitter.com/metaanalysisde", "youtube": "https://youtube.com/metaanalysisde"}', false, true, 50.00, 195.00, 1500),
('FortniteClipsDE', 'FORTNITECLIPS', 'FortniteClipsDE', 'https://i.pravatar.cc/150?img=15', 'Highlights und Clips aus der deutschen Community. Die besten Plays, Funny Moments und Pro-Clips.', '{"twitter": "https://twitter.com/fortniteclipsde", "youtube": "https://youtube.com/fortniteclipsde", "tiktok": "https://tiktok.com/fortniteclipsde"}', false, true, 50.00, 175.25, 1400),
('ZoneWarsDE', 'ZONEWARS', 'ZoneWarsDE', 'https://i.pravatar.cc/150?img=16', 'Zone Wars Spezialist. Zone Wars Strategien, Tips und Tricks für Competitive Zone Wars Matches.', '{"twitter": "https://twitter.com/zonewarsde", "youtube": "https://youtube.com/zonewarsde"}', false, true, 50.00, 160.00, 1300),
('BuildFightDE', 'BUILDFIGHT', 'BuildFightDE', 'https://i.pravatar.cc/150?img=17', 'Build Fight Expert. Box Fighting, Edit-Courses und Advanced Building-Techniken für Competitive Players.', '{"twitter": "https://twitter.com/buildfightde", "youtube": "https://youtube.com/buildfightde"}', false, true, 50.00, 145.75, 1200),
('ControllerProDE', 'CONTROLLERPRO', 'ControllerProDE', 'https://i.pravatar.cc/150?img=18', 'Controller-Spezialist. Aim Assist, Controller-Settings und Competitive Controller-Strategien.', '{"twitter": "https://twitter.com/controllerprode", "youtube": "https://youtube.com/controllerprode"}', false, true, 50.00, 130.50, 1100),
('TacticalDE', 'TACTICAL', 'TacticalDE', 'https://i.pravatar.cc/150?img=19', 'Tactical Gameplay Spezialist. Positioning, Rotations und Late-Game-Strategien für Competitive Matches.', '{"twitter": "https://twitter.com/tacticalde", "youtube": "https://youtube.com/tacticalde"}', false, true, 50.00, 120.00, 1000),
('FortniteTipsDE', 'FORTNITETIPS', 'FortniteTipsDE', 'https://i.pravatar.cc/150?img=20', 'All-round Fortnite-Tips für alle Spieler. Quick-Tips, Tricks und tägliche Verbesserungen für dein Gameplay.', '{"twitter": "https://twitter.com/fortnitetipsde", "youtube": "https://youtube.com/fortnitetipsde"}', false, true, 50.00, 110.25, 900);

ON CONFLICT (creator_code) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  avatar_url = EXCLUDED.avatar_url,
  bio = EXCLUDED.bio,
  social_links = EXCLUDED.social_links,
  is_verified = EXCLUDED.is_verified,
  is_active = EXCLUDED.is_active,
  revenue_share_percentage = EXCLUDED.revenue_share_percentage,
  total_revenue = EXCLUDED.total_revenue,
  total_code_uses = EXCLUDED.total_code_uses,
  updated_at = NOW();
